SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';


-- -----------------------------------------------------
-- Table `USUARIO`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `USUARIO` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `NOME` VARCHAR(45) NOT NULL ,
  `TELEFONE` VARCHAR(45) NULL ,
  `DATA_NASCIMENTO` DATE NULL ,
  `DATA_HORA_CRIACAO` DATETIME NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FILHOS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `FILHOS` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `NOME` VARCHAR(45) NOT NULL ,
  `USUARIO_ID` INT UNSIGNED NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `IDX_FILHOS_USUARIO` (`USUARIO_ID` ASC) ,
  CONSTRAINT `IDX_FILHOS_USUARIO`
    FOREIGN KEY (`USUARIO_ID` )
    REFERENCES `USUARIO` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USUARIO_has_FILHOS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `USUARIO_has_FILHOS` (
  `USUARIO_ID` INT UNSIGNED NOT NULL ,
  `FILHOS_ID` INT UNSIGNED NOT NULL ,
  PRIMARY KEY (`USUARIO_ID`, `FILHOS_ID`) ,
  INDEX `IDX_USUARIO_has_FILHOS_FILHOS1` (`FILHOS_ID` ASC) ,
  INDEX `IDX_USUARIO_has_FILHOS_USUARIO1` (`USUARIO_ID` ASC) ,
  CONSTRAINT `IDX_USUARIO_has_FILHOS_USUARIO1`
    FOREIGN KEY (`USUARIO_ID` )
    REFERENCES `USUARIO` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDX_USUARIO_has_FILHOS_FILHOS1`
    FOREIGN KEY (`FILHOS_ID` )
    REFERENCES `FILHOS` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE  TABLE EXEMPLO (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `TIPO_VARCHAR` VARCHAR(45) NOT NULL ,
  `TIPO_INTEIRO` INT NULL ,
  `TIPO_LONG` BIGINT NULL ,
  `TIPO_DATA` DATE NULL ,
  `TIPO_HORA` TIME NULL ,
  `TIPO_DATAHORA` DATETIME NULL ,
  `TIPO_TIMESTAMP` TIMESTAMP NULL DEFAULT NOW() ,
  `TIPO_DECIMAL` DECIMAL(10,2) NULL ,
  `TIPO_BOOLEAN` TINYINT(1) NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `TIPO_VARCHAR_UNIQUE` (`TIPO_VARCHAR` ASC) )
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

